// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace OnlineShoppingCart.Models
{
    public partial class ActivationCode
    {
        public int Id { get; set; }
        public int? ProductId { get; set; }
        public int? OrderDetailsId { get; set; }
    }
}