// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace OnlineShoppingCart.Models
{
    public partial class Cart
    {
        public Cart()
        {
            CartDetails = new HashSet<CartDetails>();
            Payment = new HashSet<Payment>();
        }

        public int Id { get; set; }
        public string UserId { get; set; }
        public DateTime? DateTime { get; set; }

        public virtual ICollection<CartDetails> CartDetails { get; set; }
        public virtual ICollection<Payment> Payment { get; set; }
    }
}