// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace OnlineShoppingCart.Models
{
    public partial class CartDetails
    {
        public int Id { get; set; }
        public int CartId { get; set; }
        public int ProductId { get; set; }
        public int? Qty { get; set; }
        public decimal? TotalPrice { get; set; }
        public int? CouponId { get; set; }

        public virtual Cart Cart { get; set; }
        public virtual Coupon Coupon { get; set; }
        public virtual Product Product { get; set; }
    }
}