// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace OnlineShoppingCart.Models
{
    public partial class Coupon
    {
        public Coupon()
        {
            CartDetails = new HashSet<CartDetails>();
        }

        public int Id { get; set; }
        public string CouponName { get; set; }
        public decimal? CouponValue { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }

        public virtual ICollection<CartDetails> CartDetails { get; set; }
    }
}