// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace OnlineShoppingCart.Models
{
    public partial class ProductReview
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public string Review { get; set; }
        public string UserId { get; set; }
        public string Rating { get; set; }
        public string UserName { get; set; }

        public virtual Product Product { get; set; }
    }
}