// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace OnlineShoppingCart.Models
{
    public partial class ProductTemp
    {
        public ProductTemp()
        {
           
        }

        public string Id { get; set; }   
        public string Quantity { get; set; }
       
    }
}