// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace OnlineShoppingCart.Models
{
    public partial class ProductCategories
    {

        public ProductCategories()
        {
            Product = new HashSet<Product>();

        }

        public int Id { get; set; }
        public string CategoryName { get; set; }
        public string CategoryDesc { get; set; }
        public string NavUrl { get; set; }
        public int? ParentId { get; set; }

        public virtual ICollection<Product> Product { get; set; }
    }

}